model:
  latent_dim: 32
  hidden_dim: 128
  rnn_type: "gru"
  input_dim: 34
  num_classes: 2
  num_mlp_iter: 5
  n_embd: 128
  block_size: 256
  num_layers: 8
  num_heads: 8

advice_model:
  hidden_dim: 512
  n_layer: 6
  n_head: 8
  n_embd: 512
  block_size: 8
  batch_size: 4
  vocab_size: 100260
  warmup_iters: 2500
  lr_decay_iters: 15000
  min_lr: 0.0001
  learning_rate: 0.001

data:
  window_size: 32
  video_script_json: "../dataset/dataset_"
  json_dir: "../dataset/skeleton_data"
  eval_json_dir: "../dataset/skeleton_eval"
  predicted_json_path: "../dataset/skeleton_predict_json"
  # skeleton_video_path: "../dataset/skeleton_data"
  skeleton_video_base_path: "../dataset"
  predicted_video_path: "../dataset/predicted_video"
  extracted_json_path: "../dataset/extracted_json"
  extracted_video_path: "../dataset/extracted_video"
  mode: 1 # default
  inference_mode: 1 # 0 for inference, 1 for training
  aligned_json_path: "../dataset/aligned_json"
  combined_video_path: "../dataset/combined_video"
  advice_csv_path: "../dataset/Pose_advice/pose_advice.csv"
  max_seq_len: 64
  pad_token_id: 100258
  begin_token_id: 100259
  device: "cuda" 
  keypoint_distance_threshold: 25
  keypoint_distance_json_path: "../dataset/keypoint_distance_json"

training:
  batch_size: 4
  num_epochs: 200
  learning_rate: 0.0003
  beta: 0.001
  confidence_threshold: 0.1
  warmup_iters: 50
  lr_decay_iters: 150
  min_lr: 0.0001
  # iters: 5000
  ckpt_path: "../ckpt/"
  eval_interval: 10
  lambda_smooth: 0.1
  beta: 0.01
  beta_start: 0.0
  beta_growth: 0.002
  max_iters: 30000


device: "cuda"

video_info:
  width: 1440
  height: 1080
  fps: 30.0

