model:
  latent_dim: 32
  hidden_dim: 128
  rnn_type: "gru"
  input_dim: 51
  num_classes: 2
  num_mlp_iter: 5

data:
  window_size: 8
  video_script_json: "../dataset/dataset_"
  json_dir: "../dataset/skeleton_data"
  eval_json_dir: "../dataset/skeleton_eval_1"
  # skeleton_video_path: "../dataset/skeleton_data"
  skeleton_video_base_path: "../dataset"

training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 0.001
  beta: 0.001
  confidence_threshold: 0.1
  warmup_iters: 300
  lr_decay_iters: 3000
  min_lr: 0.0001
  # iters: 5000
  ckpt_path: "../ckpt/"
  eval_interval: 50

device: "cuda"